### ISSUE TITLE
Using other network mode throws error

### ISSUE THREAD

**Issue by tomverelst** [tomverelst/prommer#7]
When using another network than a bridge network, the following exception occurs.

```
prommer_1           | panic: runtime error: invalid memory address or nil pointer de
reference
prommer_1           | [signal 0xb code=0x1 addr=0x0 pc=0x476524]
prommer_1           |
prommer_1           | goroutine 33 [running]:
prommer_1           | panic(0x7ddf00, 0xc820010060)
prommer_1           |   /usr/local/opt/go/libexec/src/runtime/panic.go:481 +0x3e6
prommer_1           | github.com/tomverelst/prommer/lib.(*ServiceProvider).convert(0
xc820278900, 0xc820066340, 0x40, 0xc820066380, 0x1, 0x4, 0xc820064280, 0x18, 0xc8200
720a0, 0x47, ...)
prommer_1           |  <redacted>/go/src/github.com/tomverelst/prommer/lib/s
ervice_provider.go:102 +0x284
prommer_1           | github.com/tomverelst/prommer/lib.(*ServiceProvider).GetServic

es(0xc820278900, 0x0, 0x0, 0x0, 0x0, 0x0)
prommer_1           |   <redacted>/go/src/github.com/tomverelst/prommer/lib/s
ervice_provider.go:70 +0x630
prommer_1           | github.com/tomverelst/prommer/lib.(*Prommer).Start(0xc82027892
0)
prommer_1           |   <redacted>t/go/src/github.com/tomverelst/prommer/lib/p
rommer.go:47 +0x29
prommer_1           | created by main.main
prommer_1           |   <redacted>/go/src/github.com/tomverelst/prommer/main.
go:25 +0xe6
```

**Comment by tomverelst** [comment]
Related to #6

**Comment by tomverelst** [comment]
Fixed in https://github.com/tomverelst/prommer/commit/a8ae99335bdca6d507ab11a2ec7c431a0c94baef
